name: 'github apps test'
on:
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: chihiro-adachi
          repositories: |
            test-github-apps-target
      - name: Use token
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh repo clone chihiro-adachi/test-github-apps-target
          ls -la
          cd test-github-apps-target
          git checkout -b temp-1234 origin/main
          echo 123 >> test.txt
          git commit -m "test 123"
          
