name: 'github apps test'
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: chihiro-adachi
          repositories: |
            test-github-apps-target
      - uses: actions/checkout@v4
        with:
          repository: chihiro-adachi/test-github-apps-target
          path: test-github-apps-target
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - name: Create PR
        working-directory: test-github-apps-target
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "git@github.com"
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"

          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/chihiro-adachi/test-github-apps-target"
          git remote -v

          git config --global user.email "chihiro-adachi@example.com"
          git config --global user.name "Chihiro Adachi"
          git checkout -b temp-1234 origin/main
          echo 123 >> test.txt
          git add .
          git commit -m "test 123"
          git push origin temp-1234
