name: 'github apps test'
on:
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: chihiro-adachi
          repositories: |
            test-github-apps-target
      - name: Use token
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
