name: 'github apps test'
on:
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: chihiro-adachi
          #repositories: |
          #  test-github-apps-target
      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          BRANCH: temp-1234
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Chihiro Adachi"
          
          CLONE_DIR=$(mktemp -d)
          git clone https://x-access-token:${GH_TOKEN}@github.com/chihiro-adachi/test-github-apps-target.git ${CLONE_DIR}
          cd ${CLONE_DIR}
          git checkout -b ${BRANCH} origin/main
          echo 123 >> test.txt
          git add test.txt
          git commit -m "test 123"
          git push origin ${BRANCH}
          #gh pr create --fill --base main --head ${BRANCH}
