name: 'github apps test'
on:
  push:
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: chihiro-adachi
          #repositories: |
          #  test-github-apps-target
      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/chihiro-adachi/".insteadOf git@github.com:chihiro-adachi/
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
  
          gh repo clone chihiro-adachi/test-github-apps-target
          ls -la
          cd test-github-apps-target
          git checkout -b temp-1234 origin/main
          echo 123 >> test.txt
          git add .
          git commit -m "test 123"
